### PR TITLE
Update dependencies for PHP 7.4 compatibility

### PR DESCRIPTION
**Pull request by xini**

### CODE REVIEW

**Comment by bummzack** [comment]
Thanks for the PR, but is this necessary? `^0.1` will also install `0.2`

**Comment by xini** [comment]
Thanks @bummzack. Unfortunately not. I get the following error when updating:
```
  Problem 1
    - bummzack/silverstripe-emogrify 0.1.2 requires bummzack/swiftmailer-emogrifyplugin ^0.1 -> satisfiable by bummzack/swiftmailer-emogrifyplugin[0.1].
    - bummzack/silverstripe-emogrify 0.1.2 requires bummzack/swiftmailer-emogrifyplugin ^0.1 -> satisfiable by bummzack/swiftmailer-emogrifyplugin[0.1].
    - bummzack/swiftmailer-emogrifyplugin 0.1 requires pelago/emogrifier ^2.0 -> satisfiable by pelago/emogrifier[v2.0.0, v2.1.0, v2.1.1, v2.2.0].
    - pelago/emogrifier v2.2.0 requires php ^5.5.0 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your PHP version (7.4.2) does not satisfy that requirement.
    - pelago/emogrifier v2.1.1 requires php ^5.5.0 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your PHP version (7.4.2) does not satisfy that requirement.
    - pelago/emogrifier v2.1.0 requires php ^5.5.0 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your PHP version (7.4.2) does not satisfy that requirement.
    - pelago/emogrifier v2.0.0 requires php ^5.5.0 || ~7.0.0 || ~7.1.0 || ~7.2.0 -> your PHP version (7.4.2) does not satisfy that requirement.
    - Installation request for bummzack/silverstripe-emogrify ^0.1.2 -> satisfiable by bummzack/silverstripe-emogrify[0.1.2].
```
I think it has to do with the pre-release versions (0.x). Versioning constraints even act on the miner version for pre-releases.

**Comment by bummzack** [comment]
Looks like you're right.
> For pre-1.0 versions it also acts with safety in mind and treats ^0.3 as >=0.3.0 <0.4.0.
Thanks! Will release as `0.2`

**Comment by xini** [comment]
great, thanks!

**Pull request merged**
